notifications:
  email: false
language: node_js
sudo: false
node_js: 8
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm run lint
script: xvfb-run npm run test
