notifications:
  email: false
language: node_js
sudo: false
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g polymer-cli
  - polymer install
  - npm run lint
script:
  - xvfb-run polymer test --skip-plugin sauce
